### ISSUE TITLE
Add a prefix to identify lesson plans in the ToC?

### ISSUE THREAD

**Issue by ryanpitts** [OpenNewsLabs/newsroom-security-curricula#16]
I think we should consider adding "Lesson plan: " (or "LESSON: ", or "Training plan: " or something like that) as a prefix before each lesson link in Chapter 2 in the table of contents.

![screen shot 2018-01-10 at 1 21 34 pm](https://user-images.githubusercontent.com/56477/34796116-5e14fd7e-f609-11e7-91fd-6e664d89cb2d.png)

Seems like that would really help differentiate the material as people scan that list. Right now the lesson plans look the same as the pieces of Chapter 1. Any thoughts?

**Comment by zenmonkeykstop** [comment]
I like "Lesson:" - succinct and less likely to make lines wrap.

**Comment by ryanpitts** [comment]
works for me, I'll update the toc

**Comment by ryanpitts** [comment]
closed in https://github.com/OpenNewsLabs/newsroom-security-curricula/commit/2a1e313d651c9fb940043427db9345f2c3aee7e2
