### ISSUE TITLE
Do we still need the wiki resource page?

### ISSUE THREAD

**Issue by amandabee** [OpenNewsLabs/newsroom-security-curricula#9]
In preparation for the June convening, we aggregated a lot of resources at 
https://github.com/OpenNewsLabs/newsroom-security-curricula/wiki/Existing-Resources we need to confirm that those resources were indeed migrated to  [Chapter 3: Resources](/blob/master/docs/Chapter03-Resources.md), and replace that wiki page with a note directing folks to  [Chapter 3: Resources](/blob/master/docs/Chapter03-Resources.md).

**Comment by zenmonkeykstop** [comment]
Can someone add me to the project so that I can grab this?

**Comment by ryanpitts** [comment]
@zenmonkeykstop added! (Sorry to take a couple days, have been out for the holidays)

**Comment by zenmonkeykstop** [comment]
Working on this now, some good links still in the wiki

**Comment by zenmonkeykstop** [comment]
Wiki page contents added to resources page, wiki page updated.
